server:
  port: 8085
logging:
  level:
    com.david: INFO
person:
  id: 1
  name: 哈哈哈
  hobby:
    - 吃
    - 睡
  map: { k1: v1,k2: v2 }
  pet:
    name: 旺财
    type: 狗子

spring:
  profiles:
    active: @profiles.active@
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/master1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver